### ISSUE TITLE
It's time for 1.8/1.9 support in Parser to die

### ISSUE THREAD

**Issue by whitequark** [whitequark/parser#375]
- [x] Remove all 1.8-specific feature checks
 - [x] Remove all 1.9-specific feature checks because it makes no sense to keep that in either
 - [x] Update README to say "runs on all versions of Ruby since 2.0, and historically, all versions of Ruby since 1.8"

**Comment by bbatsov** [comment]
Finally! :-)

**Comment by alexdowad** [comment]
Should `parser` still be able to *parse* Ruby 1.8 code? Or will people who want to do that have to use an older version?

**Comment by whitequark** [comment]
> Should parser still be able to parse Ruby 1.8 code? Or will people who want to do that have to use an older version?

Of course. Now and forever.

**Comment by cremno** [comment]
Shouldn't this issue be re-opened? It sounds like “removal of 1.x-specific feature checks” also means removing `defined?(Encoding)`, `respond_to?`, etc. which are still there.

**Comment by marcandre** [comment]
@cremno: Probably best to open a PR with the simplifications you can spot

**Comment by alexdowad** [comment]
Looks like `grep` failed me. :wink:
